server:
  port: 5000

spring:
#  h2:
#    console:
#      enable: true
#      path: /h2-console
  mustache:
    suffix: .html
  datasource:
    name: testalcls_db
    initialize: false
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://testalcls.c1rtods90p7d.ap-northeast-2.rds.amazonaws.com:3306/testalcls_db?useUnicode=yes&characterEncoding=UTF-8;
    username: alcls
    password: akstnanrkd
  data:
    maria:
      #jdbc-url: jdbc:mariadb://testalcls.c1rtods90p7d.ap-northeast-2.rds.amazonaws.com:3306/testalcls_db?useUnicode=yes&characterEncoding=UTF-8
      #driver-class-name: org.mariadb.jdbc.Driver
      #username: alcls
      #password: akstnanrkd

  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.H2Dialect
        #format_sql: true
        #show_sql: true
        #temp:
          #use_jdbc_metadata_defaults: false
    generate-ddl: true
        #ddl-auto:




